services:
  frontend:
    build:
      context: youtube-sharing-fe
    env_file:
      - youtube-sharing-fe/.env
    ports:
      - 3000:3000

  server:
    container_name: server
    build:
      context: youtube-sharing-be
      args:
        NODE_PORT: 3000
    ports:
      - 8080:8080
    depends_on:
      - mongo
    env_file:
      - youtube-sharing-be/.env

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=youtube
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
