services:
  frontend:
    container_name: youtube-sharing-fe
    build:
      context: youtube-sharing-fe
    env_file:
      - youtube-sharing-fe/.env
    ports:
      - 3000:3000

  server:
    container_name: youtube-sharing-be
    build:
      context: youtube-sharing-be
      args:
        NODE_PORT: 3000
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    env_file:
      - youtube-sharing-be/.env

  mongodb:
    container_name: youtube-sharing-mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=youtube
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secret
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongodb

volumes:
  mongo_data:
